# Generated by Django 5.0.1 on 2024-03-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bioimpedance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutriId', models.BigIntegerField()),
                ('patientId', models.BigIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bodyFat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscleRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fatFreeDough', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subcutaneosFat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visceralFat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bodyWater', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skeletalMuscleMass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boneMass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscleMass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basalMetabolicRate', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'db_table': 'bioimpedance',
            },
        ),
    ]
