# Generated by Django 5.0.1 on 2024-03-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientsId', models.BigIntegerField()),
                ('nutriId', models.BigIntegerField()),
                ('shoulder', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forearm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calf', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'patients_measures',
            },
        ),
    ]
