# Generated by Django 5.0.7 on 2024-08-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientsId', models.BigIntegerField()),
                ('nutriId', models.BigIntegerField()),
                ('triceps', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subscapularis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('biceps', models.DecimalField(decimal_places=2, max_digits=5)),
                ('axiliaryMedia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thoracic', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supraIliac', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medialCalf', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'folds',
            },
        ),
    ]
