# Generated by Django 5.0.1 on 2024-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('address', models.CharField()),
                ('city', models.CharField()),
                ('occupation', models.CharField()),
                ('obs', models.CharField()),
                ('phoneContact', models.CharField()),
                ('gender', models.CharField()),
            ],
            options={
                'db_table': 'Patients',
            },
        ),
    ]
