# Generated by Django 5.0.1 on 2024-03-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients_nutriid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
    ]
