# Generated by Django 5.0.1 on 2024-03-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patients_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patients',
            table='patients',
        ),
    ]
